#========================================
# Integration test specific settings
#========================================
#----------------------------------------
# Camunda
#----------------------------------------

camunda:
  bpm:
    client:
      base-url: http://replaced_by_test:8080
  
#----------------------------------------
# Integration settings
#----------------------------------------
config:
  camunda:
    base-url: http://localhost:${wiremock.server.port}/api-camunda/engine-rest
