#========================================
# Unit test specific settings
#========================================
#----------------------------------------
# Camunda
#----------------------------------------
camunda:
  bpm:
    client:
      base-url: base.url
      disable-auto-fetching: true
    deployment:
      autoDeployEnabled: false
      processes:
        - name: process_name_1
          tenant: tenant_id_1
          bpmnResourcePattern: bpmnResourcePattern_1
          dmnResourcePattern: dmnResourcePattern_1
          formResourcePattern: formResourcePattern_1
        - name: process_name_2
          tenant: tenant_id_2
          bpmnResourcePattern: bpmnResourcePattern_2
          dmnResourcePattern: dmnResourcePattern_2
          formResourcePattern: formResourcePattern_2
  process:
    wait-duration: R/PT10S

#----------------------------------------
# Integration settings
#----------------------------------------
config:
  common:
    client-id: client-id
    client-secret: client-secret
    token-uri: token.url
  camunda:
    base-url: camunda.url
  comfactfacade:
    client-id: ${config.common.client-id}
    client-secret: ${config.common.client-secret}
    base-url: comfactfacade.url
    token-uri: ${config.common.token-uri}
  document:
    client-id: ${config.common.client-id}
    client-secret: ${config.common.client-secret}
    base-url: document.url
    token-uri: ${config.common.token-uri}

integration:
  comfactfacade:
    connectTimeout: 1
    readTimeout: 2
    url: ${config.comfactfacade.base-url}
  document:
    connectTimeout: 3
    readTimeout: 4
    url: ${config.document.base-url}
