spring:
  application:
    name: pw-e-signing
  security:
    oauth2:
      client:
        provider:
          comfactfacade:
            token-uri: ${config.comfactfacade.token-uri}
        registration:
          comfactfacade:
            authorization-grant-type: client_credentials
            provider: comfactfacade
            client-id: ${config.comfactfacade.client-id}
            client-secret: ${config.comfactfacade.client-secret}

#----------------------------------------
# Open API
#----------------------------------------
openapi:
  name: ${spring.application.name}
  title: ${spring.application.name}
  version: '@project.version@'

#----------------------------------------
# Camunda
#----------------------------------------
camunda:
  bpm:
    client:
      base-url: ${config.camunda.base-url}
      backoff:
        initTime: 500
        factor: 2
        maxTime: 15000
    deployment:
      processes:
        - name: E-signing process
          tenant: E_SIGNING
          bpmnResourcePattern: classpath*:processmodels/*.bpmn
          dmnResourcePattern: classpath*:processmodels/*.dmn
          formResourcePattern: classpath*:processmodels/*.form
  worker:
    max:
      retries: 3
    retry:
      timeout: 10
  process:
    wait-duration: 0 0 * * * *

#----------------------------------------
# Integration settings
#----------------------------------------
integration:
  camunda:
    connectTimeout: 5
    readTimeout: 20
    url: ${config.camunda.base-url}
  comfactfacade:
    connectTimeout: 5
    readTimeout: 20
    url: ${config.comfactfacade.base-url}
    