#========================================
# Integration test specific settings
#========================================
#----------------------------------------
# Camunda
#----------------------------------------

camunda:
  bpm:
    client:
      base-url: http://replaced_by_test:8080
  process:
    wait-duration: '* * * ? * *'
  
#----------------------------------------
# Integration settings
#----------------------------------------
config:
  common:
    token-uri: http://localhost:${wiremock.server.port}/api-gateway/token
    client-id: the-client-id
    client-secret: the-client-secret
  camunda:
    base-url: http://localhost:${wiremock.server.port}/api-camunda/engine-rest
  comfactfacade:
    client-id: ${config.common.client-id}
    client-secret: ${config.common.client-secret}
    base-url: http://localhost:${wiremock.server.port}/api-comfactfacade
    token-uri: ${config.common.token-uri}
    
    
    